/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soandethi;

import model.MonHoc;
import docghidulieu.DocGhiDuLieu;
import docghidulieu.PhuongThucChung;
import docghidulieu.TaoThuMucChua;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Quan
 */
public class QuanLyMonHoc extends javax.swing.JFrame {

    public static final String PATH = "src\\data\\dsmonhoc.txt";
    ArrayList<MonHoc> dsmh;
    DefaultListModel<String> dlDSMonHoc;
    DocGhiDuLieu docGhiDuLieu;
    MonHoc mh;
    TaoThuMucChua taoThuMucChua;

    /**
     * Creates new form QuanLyMonHoc
     */
    public QuanLyMonHoc() {
        initComponents();
        dlDSMonHoc = new DefaultListModel();
        listDSMonHoc.setModel(dlDSMonHoc);

        System.out.println(listDSMonHoc.getSelectedIndex());
        docGhiDuLieu = new DocGhiDuLieu();
        docDSMH();
        taoThuMucChua = new TaoThuMucChua();
    }

    public void docDSMH() {
        dsmh=new ArrayList<MonHoc>();
        dsmh = docGhiDuLieu.docFile(PATH);
        for (MonHoc mh : dsmh) {
            dlDSMonHoc.addElement(mh.getTenMonHoc());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDSMonHoc = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtTenMonHoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaHocPhan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spSoChuong = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();
        btnThemMonHoc = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnXoaMonHoc = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách môn học");

        listDSMonHoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listDSMonHoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDSMonHoc.setToolTipText("");
        listDSMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDSMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listDSMonHoc);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã học phần:");

        txtTenMonHoc.setForeground(java.awt.Color.gray);
        txtTenMonHoc.setText("Bạn hãy nhập tên môn học");
        txtTenMonHoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtTenMonHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenMonHocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenMonHocFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên môn học:");

        txtMaHocPhan.setForeground(java.awt.Color.gray);
        txtMaHocPhan.setText("Bạn hãy nhập mã học phần");
        txtMaHocPhan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtMaHocPhan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaHocPhanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaHocPhanFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Số chương:");

        spSoChuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Giới thiệu:");

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setLineWrap(true);
        txtGioiThieu.setRows(5);
        txtGioiThieu.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtGioiThieu);

        btnThemMonHoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemMonHoc.setForeground(java.awt.Color.blue);
        btnThemMonHoc.setText("<HTML><U>Thêm môn học</U></HTML>");
        btnThemMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMonHocMouseClicked(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(255, 255, 204));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(255, 204, 204));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXoaMonHoc.setBackground(java.awt.Color.red);
        btnXoaMonHoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaMonHoc.setText("Xóa môn học");
        btnXoaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonHocActionPerformed(evt);
            }
        });

        btnOk.setBackground(new java.awt.Color(204, 255, 255));
        btnOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 204, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoaMonHoc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtMaHocPhan)
                                    .addComponent(txtTenMonHoc, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLuu)
                        .addComponent(btnHuy)
                        .addComponent(btnSua)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaMonHoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenMonHocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenMonHocFocusGained
        // TODO add your handling code here:
        if (txtTenMonHoc.getText().equals("Bạn hãy nhập tên môn học")) {
            txtTenMonHoc.setText("");
            txtTenMonHoc.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtTenMonHocFocusGained

    private void txtTenMonHocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenMonHocFocusLost
        // TODO add your handling code here:
        if (txtTenMonHoc.getText().isEmpty()) {
            txtTenMonHoc.setText("Bạn hãy nhập tên môn học");
            txtTenMonHoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTenMonHocFocusLost

    private void txtMaHocPhanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaHocPhanFocusGained
        // TODO add your handling code here:
        if (txtMaHocPhan.getText().equals("Bạn hãy nhập mã học phần")) {
            txtMaHocPhan.setText("");
            txtMaHocPhan.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtMaHocPhanFocusGained

    private void txtMaHocPhanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaHocPhanFocusLost
        // TODO add your handling code here:
        if (txtMaHocPhan.getText().isEmpty()) {
            txtMaHocPhan.setText("Bạn hãy nhập mã học phần");
            txtMaHocPhan.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtMaHocPhanFocusLost

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        TrangChu f = new TrangChu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        MonHoc mhNew = new MonHoc(txtMaHocPhan.getText(), txtTenMonHoc.getText(), Integer.parseInt(spSoChuong.getValue().toString()), txtGioiThieu.getText());
        dlDSMonHoc.addElement(txtTenMonHoc.getText());
        dsmh.add(mhNew);
//        if(dlDSMonHoc.getSize()!=0){
//            btnXoaMonHoc.setEnabled(true);
//            btnXoaMonHoc.setToolTipText("");
//        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void listDSMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDSMonHocMouseClicked
        // TODO add your handling code here:
        if (listDSMonHoc.getSelectedIndex() != -1) {
            txtTenMonHoc.setText(dsmh.get(listDSMonHoc.getSelectedIndex()).getTenMonHoc());
            txtTenMonHoc.setForeground(Color.red);
            txtMaHocPhan.setText(dsmh.get(listDSMonHoc.getSelectedIndex()).getMaMonHoc());
            txtMaHocPhan.setForeground(Color.red);
            spSoChuong.setValue(dsmh.get(listDSMonHoc.getSelectedIndex()).getSoChuong());
            txtGioiThieu.setText(dsmh.get(listDSMonHoc.getSelectedIndex()).getGioiThieu());
            txtGioiThieu.setForeground(Color.red);
        }
    }//GEN-LAST:event_listDSMonHocMouseClicked

    private void btnThemMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMonHocMouseClicked
        // TODO add your handling code here:
        txtTenMonHoc.setText("Bạn hãy nhập tên môn học");
        txtTenMonHoc.setForeground(Color.gray);
        txtMaHocPhan.setText("Bạn hãy nhập mã học phần");
        txtMaHocPhan.setForeground(Color.gray);
        spSoChuong.setValue(1);
        txtGioiThieu.setText("");
    }//GEN-LAST:event_btnThemMonHocMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        taoThuMucChua.taoThuMuc(dsmh);
        docGhiDuLieu.luuFile(dsmh, PATH);
        
        //chỉ dispose thôi, vì nếu new thì sẽ có 2 trang chủ
//        Frame1 f = new Frame1();
//        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnXoaMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonHocActionPerformed
        // TODO add your handling code here:
        if (listDSMonHoc.getSelectedIndex() != -1) {
            int index = listDSMonHoc.getSelectedIndex();
            dlDSMonHoc.remove(listDSMonHoc.getSelectedIndex());
            //System.out.println(index);
            dsmh.remove(index);
            txtTenMonHoc.setText("Bạn hãy nhập tên môn học");
            txtTenMonHoc.setForeground(Color.gray);
            txtMaHocPhan.setText("Bạn hãy nhập mã học phần");
            txtMaHocPhan.setForeground(Color.gray);
            spSoChuong.setValue(1);
            txtGioiThieu.setText("");
            if (dlDSMonHoc.getSize() == 0) {
                btnXoaMonHoc.setEnabled(false);
                btnXoaMonHoc.setToolTipText("Không có môn học nào trong danh sách");
            }
        }
    }//GEN-LAST:event_btnXoaMonHocActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        MonHoc mh = new MonHoc(txtMaHocPhan.getText().toString(), txtTenMonHoc.getText().toString(), Integer.parseInt(spSoChuong.getValue().toString()), txtGioiThieu.getText().toString());
        int viTriMonHocDuocChon = listDSMonHoc.getSelectedIndex();
        dsmh.remove(viTriMonHocDuocChon);
        dsmh.add(viTriMonHocDuocChon, mh);
        
        dlDSMonHoc.remove(viTriMonHocDuocChon);
        dlDSMonHoc.add(viTriMonHocDuocChon, txtTenMonHoc.getText());
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        PhuongThucChung.quayVeTrangChu();
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel btnThemMonHoc;
    private javax.swing.JButton btnXoaMonHoc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listDSMonHoc;
    private javax.swing.JSpinner spSoChuong;
    private javax.swing.JTextArea txtGioiThieu;
    private javax.swing.JTextField txtMaHocPhan;
    private javax.swing.JTextField txtTenMonHoc;
    // End of variables declaration//GEN-END:variables
}
