/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soandethi;

import docghidulieu.DocGhiCauHoi;
import docghidulieu.DocGhiDuLieu;
import docghidulieu.PhuongThucChung;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import model.DapAn;
import model.MonHoc;
import model.TracNghiem;
import model.TuLuan;
import static soandethi.QuanLyMonHoc.PATH;

/**
 *
 * @author Quan
 */
public class SoanCauHoi extends javax.swing.JFrame {

    DefaultListModel<String> dlCauHoiTuLuan;
    DefaultListModel<String> dlCauHoiTracNghiem;

    public static DefaultListModel<String> dlDapAnTracNghiem;
    ArrayList<MonHoc> dsmh;
    DocGhiDuLieu docGhiDuLieu;

    static final String PATH = "src\\data\\dsmonhoc.txt";

    ArrayList<TuLuan> dsCauHoiTuLuan;
    ArrayList<TracNghiem> dsCauHoiTracNghiem;

    DocGhiCauHoi docGhiCauHoi;

    public String PATH_CAUHOI_TU_LUAN;
    public String PATH_CAUHOI_TRAC_NGHIEM;

    public static ArrayList<DapAn> dsDapAn;

    static String cauHoiTracNghiemDuocLuaChon;

    /**
     * Creates new form SoanCauHoi
     */
    public SoanCauHoi() {
        initComponents();
        dsmh = new ArrayList<>();
        docGhiDuLieu = new DocGhiDuLieu();
        dsmh = docGhiDuLieu.docFile(PATH);
        hienThiTenCuaMonHocDuocChon();

        MonHoc mh = dsmh.get(ChonMonHoc.viTriMonHocDuocChon);
        PATH_CAUHOI_TU_LUAN = "src\\data\\" + mh.getTenMonHoc() + "\\TuLuan.txt";
        PATH_CAUHOI_TRAC_NGHIEM = "src\\data\\" + mh.getTenMonHoc() + "\\TracNghiem.txt";
        
        dsCauHoiTuLuan = new ArrayList<>();
        docGhiCauHoi = new DocGhiCauHoi();
        dlCauHoiTuLuan = new DefaultListModel();
        docDSCauHoiTuLuan();
        listCauHoiTuLuan.setModel(dlCauHoiTuLuan);

        dsCauHoiTracNghiem = new ArrayList<>();
        dlDapAnTracNghiem = new DefaultListModel<>();
        dlCauHoiTracNghiem = new DefaultListModel<>();
        listDapAnTracNghiem.setModel(dlDapAnTracNghiem);

        docDSCauHoiTracNghiem();
        listCauHoiTracNghiem.setModel(dlCauHoiTracNghiem);
        
        
        
        dsDapAn = new ArrayList<>();
    }
//     private void layViTriMonHocDuocChon() {
//        viTriMonHocDuocChon = cbDSMonHoc.getSelectedIndex();
//                System.out.println(""+viTriMonHocDuocChon);
//    }

    public void docDSCauHoiTuLuan() {
        dsCauHoiTuLuan = docGhiCauHoi.docCauHoiTuLuan(PATH_CAUHOI_TU_LUAN);
        for (TuLuan tl : dsCauHoiTuLuan) {
            dlCauHoiTuLuan.addElement(tl.getNoiDungCauHoi());
        }
    }

    public void docDSCauHoiTracNghiem() {
        dsCauHoiTracNghiem = docGhiCauHoi.docCauHoiTracNghiem(PATH_CAUHOI_TRAC_NGHIEM);

        for (TracNghiem tn : dsCauHoiTracNghiem) {
            //System.out.println("123");
            dlCauHoiTracNghiem.addElement(tn.getNoiDungCauHoi());
            // System.out.println("123");
        }

    }

    private void hienThiTenCuaMonHocDuocChon() {
        System.out.println("Vị trí được chọn " + ChonMonHoc.viTriMonHocDuocChon);
        MonHoc mh = dsmh.get(ChonMonHoc.viTriMonHocDuocChon);
        System.out.println("So chuong mon hoc:"+mh.getSoChuong());
        lbMonHocDuocChon.setText(mh.getTenMonHoc());
        for (int i = 1; i <= mh.getSoChuong(); i++) {
            cbChuong.addItem(String.valueOf(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCauHoiTuLuan = new javax.swing.JList<>();
        btnThemCauHoi = new javax.swing.JLabel();
        lbMonHocDuocChon = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listCauHoiTracNghiem = new javax.swing.JList<>();
        btnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rdTuLuan = new javax.swing.JRadioButton();
        rdTracNghiem = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeBai = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbDoKho = new javax.swing.JComboBox<>();
        cbChuong = new javax.swing.JComboBox<>();
        btnLuuCauHoi = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnXoaCauHoi = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGoiYDapAnTuLuan = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDapAnTracNghiem = new javax.swing.JList<>();
        btnXoaDapAnTracNghiem = new javax.swing.JButton();
        btnChinhSuaDapAnTracNghiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soạn câu hỏi");

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách câu hỏi của môn học:");

        listCauHoiTuLuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        listCauHoiTuLuan.setToolTipText("");
        listCauHoiTuLuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCauHoiTuLuanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCauHoiTuLuan);

        btnThemCauHoi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnThemCauHoi.setForeground(java.awt.Color.blue);
        btnThemCauHoi.setText("<HTML><U>Thêm câu hỏi</U></HTML>");
        btnThemCauHoi.setToolTipText("");
        btnThemCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemCauHoiMouseClicked(evt);
            }
        });

        lbMonHocDuocChon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbMonHocDuocChon.setForeground(java.awt.Color.red);

        listCauHoiTracNghiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        listCauHoiTracNghiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCauHoiTracNghiemMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listCauHoiTracNghiem);

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMonHocDuocChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(282, 282, 282))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHome)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnThemCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbMonHocDuocChon))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnThemCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Danh sách câu hỏi:");

        rdTuLuan.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rdTuLuan);
        rdTuLuan.setText("Tự luận");
        rdTuLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTuLuanActionPerformed(evt);
            }
        });

        rdTracNghiem.setBackground(new java.awt.Color(153, 255, 51));
        buttonGroup1.add(rdTracNghiem);
        rdTracNghiem.setSelected(true);
        rdTracNghiem.setText("Trắc nghiệm");
        rdTracNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTracNghiemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Đề bài:");

        txtDeBai.setColumns(20);
        txtDeBai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDeBai.setForeground(java.awt.Color.gray);
        txtDeBai.setLineWrap(true);
        txtDeBai.setRows(5);
        txtDeBai.setWrapStyleWord(true);
        txtDeBai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtDeBai);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Độ khó:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Chương:");

        cbDoKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cbChuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChuongActionPerformed(evt);
            }
        });

        btnLuuCauHoi.setBackground(new java.awt.Color(255, 204, 153));
        btnLuuCauHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuuCauHoi.setText("Lưu");
        btnLuuCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCauHoiActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(102, 255, 102));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXoaCauHoi.setBackground(java.awt.Color.red);
        btnXoaCauHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaCauHoi.setText("Xóa câu hỏi");
        btnXoaCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCauHoiActionPerformed(evt);
            }
        });

        btnOK.setBackground(new java.awt.Color(0, 255, 204));
        btnOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Gợi ý đáp án:");

        txtGoiYDapAnTuLuan.setColumns(20);
        txtGoiYDapAnTuLuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGoiYDapAnTuLuan.setLineWrap(true);
        txtGoiYDapAnTuLuan.setRows(5);
        txtGoiYDapAnTuLuan.setWrapStyleWord(true);
        txtGoiYDapAnTuLuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(txtGoiYDapAnTuLuan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Các lựa chọn đáp án:");

        listDapAnTracNghiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jScrollPane3.setViewportView(listDapAnTracNghiem);

        btnXoaDapAnTracNghiem.setBackground(new java.awt.Color(255, 153, 102));
        btnXoaDapAnTracNghiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaDapAnTracNghiem.setText("Xóa");
        btnXoaDapAnTracNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDapAnTracNghiemActionPerformed(evt);
            }
        });

        btnChinhSuaDapAnTracNghiem.setBackground(new java.awt.Color(0, 153, 0));
        btnChinhSuaDapAnTracNghiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChinhSuaDapAnTracNghiem.setText("Chỉnh sửa");
        btnChinhSuaDapAnTracNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaDapAnTracNghiemActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(102, 204, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem)
                        .addGap(13, 13, 13)
                        .addComponent(btnChinhSuaDapAnTracNghiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaDapAnTracNghiem)
                        .addGap(1, 1, 1))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChinhSuaDapAnTracNghiem, btnThem, btnXoaDapAnTracNghiem});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnChinhSuaDapAnTracNghiem)
                    .addComponent(btnXoaDapAnTracNghiem))
                .addGap(43, 43, 43))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnChinhSuaDapAnTracNghiem, btnThem, btnXoaDapAnTracNghiem});

        btnSua.setBackground(new java.awt.Color(255, 255, 153));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdTracNghiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdTuLuan))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLuuCauHoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaCauHoi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOK)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDoKho, 0, 42, Short.MAX_VALUE)
                                    .addComponent(cbChuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdTuLuan)
                    .addComponent(rdTracNghiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuCauHoi)
                    .addComponent(btnHuy)
                    .addComponent(btnXoaCauHoi)
                    .addComponent(btnSua))
                .addGap(11, 11, 11)
                .addComponent(btnOK)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdTuLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTuLuanActionPerformed
        // TODO add your handling code here:
        if (rdTuLuan.isSelected()) {
            jPanel3.setVisible(false);
            jPanel4.setVisible(true);

        } else {
            jPanel3.setVisible(true);
            jPanel4.setVisible(false);
        }
    }//GEN-LAST:event_rdTuLuanActionPerformed

    private void rdTracNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTracNghiemActionPerformed
        // TODO add your handling code here:
        if (rdTracNghiem.isSelected()) {
            jPanel4.setVisible(false);
            jPanel3.setVisible(true);

        } else {
            jPanel4.setVisible(true);
            jPanel3.setVisible(false);
        }
    }//GEN-LAST:event_rdTracNghiemActionPerformed

    private void btnLuuCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCauHoiActionPerformed
        // TODO add your handling code here:
//         String data = (String) cb.getItemAt(cb.getSelectedIndex());
        if (rdTuLuan.isSelected()) {
            TuLuan tl = new TuLuan(txtDeBai.getText().toString(), Integer.parseInt(String.valueOf(cbChuong.getItemAt(cbChuong.getSelectedIndex()))), Integer.parseInt(String.valueOf(cbDoKho.getItemAt(cbDoKho.getSelectedIndex()))), txtGoiYDapAnTuLuan.getText().toString());
            dsCauHoiTuLuan.add(tl);
            dlCauHoiTuLuan.addElement(tl.getNoiDungCauHoi());
            listCauHoiTuLuan.setModel(dlCauHoiTuLuan);
        } else {
           // dsDapAn = new ArrayList<>();
            TracNghiem tn = new TracNghiem(txtDeBai.getText(),
                    Integer.parseInt(String.valueOf(cbChuong.getItemAt(cbChuong.getSelectedIndex()))),
                    Integer.parseInt(String.valueOf(cbDoKho.getItemAt(cbDoKho.getSelectedIndex()))),
                    dsDapAn);
            dsCauHoiTracNghiem.add(tn);
            dlCauHoiTracNghiem.addElement(tn.getNoiDungCauHoi());
            listCauHoiTracNghiem.setModel(dlCauHoiTracNghiem);
        }

        if (dlCauHoiTuLuan.getSize() != 0 || dlCauHoiTracNghiem.getSize() != 0) {
            btnXoaCauHoi.setEnabled(true);
            btnXoaCauHoi.setToolTipText("");
        }
        // docGhiCauHoi.luuCauHoiTuLuan(ds, PATH)
    }//GEN-LAST:event_btnLuuCauHoiActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        docGhiCauHoi.luuCauHoiTuLuan(dsCauHoiTuLuan, PATH_CAUHOI_TU_LUAN);
        docGhiCauHoi.luuCauTracNghiem(dsCauHoiTracNghiem, PATH_CAUHOI_TRAC_NGHIEM);
        TrangChu f = new TrangChu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        TrangChu f = new TrangChu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemCauHoiMouseClicked
        // TODO add your handling code here:
        txtDeBai.setText("");
        txtGoiYDapAnTuLuan.setText("");
        cbChuong.setSelectedIndex(0);
        cbDoKho.setSelectedIndex(0);
        dlDapAnTracNghiem.removeAllElements();
    }//GEN-LAST:event_btnThemCauHoiMouseClicked

    private void btnXoaCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCauHoiActionPerformed
        // TODO add your handling code here:
        if (listCauHoiTuLuan.getSelectedIndex() != -1 && rdTuLuan.isSelected()) {
            int index = listCauHoiTuLuan.getSelectedIndex();
            dlCauHoiTuLuan.remove(listCauHoiTuLuan.getSelectedIndex());
            //System.out.println(index);
            dsCauHoiTuLuan.remove(index);
            txtDeBai.setText("Cho a =2, b=6. Tìm giá trị của x biết x=a+b.");
            txtDeBai.setForeground(Color.gray);
            txtGoiYDapAnTuLuan.setText("");
            cbChuong.setSelectedIndex(0);
            cbDoKho.setSelectedIndex(0);

        }

        if (listCauHoiTracNghiem.getSelectedIndex() != -1 && rdTracNghiem.isSelected()) {
            int index = listCauHoiTracNghiem.getSelectedIndex();
            dlCauHoiTracNghiem.remove(listCauHoiTracNghiem.getSelectedIndex());
            //System.out.println(index);
            dsCauHoiTracNghiem.remove(index);
           // txtDeBai.setText("Cho a =2, b=6. Tìm giá trị của x biết x=a+b.");
            txtDeBai.setForeground(Color.gray);
            //txtGoiYDapAnTuLuan.setText("");
            cbChuong.setSelectedIndex(0);
            cbDoKho.setSelectedIndex(0);
            dlDapAnTracNghiem.removeAllElements();

        }
        if (dlCauHoiTracNghiem.getSize() == 0 && dlCauHoiTuLuan.getSize() == 0) {
            btnXoaCauHoi.setEnabled(false);
            btnXoaCauHoi.setToolTipText("Không có câu hỏi nào trong danh sách");
        }


    }//GEN-LAST:event_btnXoaCauHoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ThemDapAnTracNghiem themDapAnTracNghiem = new ThemDapAnTracNghiem();
        themDapAnTracNghiem.setVisible(true);

    }//GEN-LAST:event_btnThemActionPerformed

    private void listCauHoiTuLuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCauHoiTuLuanMouseClicked
        // TODO add your handling code here:
        rdTuLuan.setSelected(true);
        if (rdTracNghiem.isSelected()) {
            jPanel4.setVisible(false);
            jPanel3.setVisible(true);

        } else {
            jPanel4.setVisible(true);
            jPanel3.setVisible(false);
        }
        if (listCauHoiTuLuan.getSelectedIndex() != -1) {
            txtDeBai.setText(dsCauHoiTuLuan.get(listCauHoiTuLuan.getSelectedIndex()).getNoiDungCauHoi());
            txtDeBai.setForeground(Color.red);
            txtGoiYDapAnTuLuan.setText(dsCauHoiTuLuan.get(listCauHoiTuLuan.getSelectedIndex()).getGoiYDapAn());
            txtGoiYDapAnTuLuan.setForeground(Color.red);
            cbChuong.setSelectedItem(String.valueOf(dsCauHoiTuLuan.get(listCauHoiTuLuan.getSelectedIndex()).getChuong()));
            cbDoKho.setSelectedItem(String.valueOf(dsCauHoiTuLuan.get(listCauHoiTuLuan.getSelectedIndex()).getDoKho()));
        }
    }//GEN-LAST:event_listCauHoiTuLuanMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (rdTuLuan.isSelected()) {
            TuLuan tl = new TuLuan(txtDeBai.getText().toString(),
                    Integer.parseInt(cbChuong.getItemAt(cbChuong.getSelectedIndex())),
                    Integer.parseInt(cbDoKho.getItemAt(cbDoKho.getSelectedIndex())),
                    txtGoiYDapAnTuLuan.getText().toString());

            int viTriCauHoiTuLuanDuocChon = listCauHoiTuLuan.getSelectedIndex();

            dsCauHoiTuLuan.remove(viTriCauHoiTuLuanDuocChon);
            dsCauHoiTuLuan.add(viTriCauHoiTuLuanDuocChon, tl);

            dlCauHoiTuLuan.remove(viTriCauHoiTuLuanDuocChon);
            dlCauHoiTuLuan.add(viTriCauHoiTuLuanDuocChon, txtDeBai.getText());

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cbChuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChuongActionPerformed

    private void listCauHoiTracNghiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCauHoiTracNghiemMouseClicked
        // TODO add your handling code here:
        rdTracNghiem.setSelected(true);
        if (rdTracNghiem.isSelected()) {
            jPanel4.setVisible(false);
            jPanel3.setVisible(true);

        } else {
            jPanel4.setVisible(true);
            jPanel3.setVisible(false);
        }
        if (listCauHoiTracNghiem.getSelectedIndex() != -1) {
            txtDeBai.setText(dsCauHoiTracNghiem.get(listCauHoiTracNghiem.getSelectedIndex()).getNoiDungCauHoi());
            txtDeBai.setForeground(Color.red);
          //  dsDapAn = new ArrayList<>();
            dsDapAn = dsCauHoiTracNghiem.get(listCauHoiTracNghiem.getSelectedIndex()).getDsDapAn();
            int i = 0;
            dlDapAnTracNghiem.removeAllElements();
            for (DapAn dapAn : dsDapAn) {

                dlDapAnTracNghiem.addElement(dapAn.getNoiDung().toString());
                // listDapAnTracNghiem.setModel(dlDapAnTracNghiem);

                System.out.println(dapAn.getNoiDung());
            }
            //  listDapAnTracNghiem.setText(dsCauHoiTuLuan.get(listCauHoiTuLuan.getSelectedIndex()).getGoiYDapAn());
            // txtGoiYDapAnTuLuan.setForeground(Color.red);
            listDapAnTracNghiem.setModel(dlDapAnTracNghiem);
            cbChuong.setSelectedItem(String.valueOf(dsCauHoiTracNghiem.get(listCauHoiTracNghiem.getSelectedIndex()).getChuong()));
            cbDoKho.setSelectedItem(String.valueOf(dsCauHoiTracNghiem.get(listCauHoiTracNghiem.getSelectedIndex()).getDoKho()));
            cauHoiTracNghiemDuocLuaChon = listCauHoiTracNghiem.getSelectedValue();
        }
        
                
    }//GEN-LAST:event_listCauHoiTracNghiemMouseClicked

    private void btnXoaDapAnTracNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDapAnTracNghiemActionPerformed
        // TODO add your handling code here:
        if (listDapAnTracNghiem.getSelectedIndex() != -1) {
            int i = listDapAnTracNghiem.getSelectedIndex();
            dlDapAnTracNghiem.remove(i);
            dsDapAn.remove(i);
        }
    }//GEN-LAST:event_btnXoaDapAnTracNghiemActionPerformed

    private void btnChinhSuaDapAnTracNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaDapAnTracNghiemActionPerformed
        // TODO add your handling code here:
        if (listDapAnTracNghiem.getSelectedIndex() != -1) {
            SuaDapAnTracNghiem suaDapAnTracNghiem = new SuaDapAnTracNghiem();
            suaDapAnTracNghiem.setVisible(true);
            suaDapAnTracNghiem.txtSuaDapAnTracNghiem.setText(dsDapAn.get(listDapAnTracNghiem.getSelectedIndex()).getNoiDung());
            suaDapAnTracNghiem.chkSuaDapAnDungTracNghiem.setSelected(dsDapAn.get(listDapAnTracNghiem.getSelectedIndex()).isIsTrue());
        }
    }//GEN-LAST:event_btnChinhSuaDapAnTracNghiemActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
         PhuongThucChung.quayVeTrangChu();
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoanCauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChinhSuaDapAnTracNghiem;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuuCauHoi;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel btnThemCauHoi;
    private javax.swing.JButton btnXoaCauHoi;
    private javax.swing.JButton btnXoaDapAnTracNghiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbChuong;
    private javax.swing.JComboBox<String> cbDoKho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbMonHocDuocChon;
    private javax.swing.JList<String> listCauHoiTracNghiem;
    private javax.swing.JList<String> listCauHoiTuLuan;
    public static javax.swing.JList<String> listDapAnTracNghiem;
    private javax.swing.JRadioButton rdTracNghiem;
    private javax.swing.JRadioButton rdTuLuan;
    private javax.swing.JTextArea txtDeBai;
    private javax.swing.JTextArea txtGoiYDapAnTuLuan;
    // End of variables declaration//GEN-END:variables

}
