/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soandethi;

import model.DapAn;

/**
 *
 * @author Quan
 */
public class SuaDapAnTracNghiem extends javax.swing.JFrame {
    DapAn dapAn;

    /**
     * Creates new form SuaDapAnTracNghiem
     */
    public SuaDapAnTracNghiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSuaDapAnTracNghiem = new javax.swing.JTextArea();
        chkSuaDapAnDungTracNghiem = new javax.swing.JCheckBox();
        btnHuySuaDapAnTracNghiem = new javax.swing.JButton();
        btnDongYSuaDapAnTracNghiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Sửa đáp án trắc nghiệm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nội dung");

        txtSuaDapAnTracNghiem.setColumns(20);
        txtSuaDapAnTracNghiem.setRows(5);
        jScrollPane1.setViewportView(txtSuaDapAnTracNghiem);

        chkSuaDapAnDungTracNghiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkSuaDapAnDungTracNghiem.setText("là đáp án đúng?");

        btnHuySuaDapAnTracNghiem.setBackground(new java.awt.Color(204, 255, 204));
        btnHuySuaDapAnTracNghiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHuySuaDapAnTracNghiem.setText("Hủy sửa");
        btnHuySuaDapAnTracNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuySuaDapAnTracNghiemActionPerformed(evt);
            }
        });

        btnDongYSuaDapAnTracNghiem.setBackground(new java.awt.Color(204, 204, 255));
        btnDongYSuaDapAnTracNghiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDongYSuaDapAnTracNghiem.setText("Đồng ý sửa");
        btnDongYSuaDapAnTracNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYSuaDapAnTracNghiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHuySuaDapAnTracNghiem)
                        .addGap(199, 199, 199)
                        .addComponent(btnDongYSuaDapAnTracNghiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkSuaDapAnDungTracNghiem)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkSuaDapAnDungTracNghiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuySuaDapAnTracNghiem)
                    .addComponent(btnDongYSuaDapAnTracNghiem))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuySuaDapAnTracNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuySuaDapAnTracNghiemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuySuaDapAnTracNghiemActionPerformed

    private void btnDongYSuaDapAnTracNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYSuaDapAnTracNghiemActionPerformed
        // TODO add your handling code here:
         boolean kiemTra;
        if (chkSuaDapAnDungTracNghiem.isSelected()) {
            kiemTra = true;
        } else {
            kiemTra = false;
        }
        dapAn = new DapAn(txtSuaDapAnTracNghiem.getText(), kiemTra);
        //TODO
//        ChonCauHoi.modelListDapAn.addElement(suaDA.getTenDapAn());
//        cch.listDapAn.setModel(ChonCauHoi.modelListDapAn);
        // sch = new SoanCauHoi();
        int x =SoanCauHoi.listDapAnTracNghiem.getSelectedIndex();
        SoanCauHoi.dlDapAnTracNghiem.remove(x);
     //   SoanCauHoi.dlDapAnTracNghiem.addElement(txtNoiDungDapAnTracNghiem.getText());
     SoanCauHoi.dlDapAnTracNghiem.add(x, txtSuaDapAnTracNghiem.getText());
     SoanCauHoi.dsDapAn.remove(x);
        SoanCauHoi.dsDapAn.add(x,dapAn);
        System.out.println("Vua moi sua xong \t"+x);
//       sch =new SoanCauHoi();
//       sch.

        this.dispose();
    }//GEN-LAST:event_btnDongYSuaDapAnTracNghiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaDapAnTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaDapAnTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaDapAnTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaDapAnTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaDapAnTracNghiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongYSuaDapAnTracNghiem;
    private javax.swing.JButton btnHuySuaDapAnTracNghiem;
    public static javax.swing.JCheckBox chkSuaDapAnDungTracNghiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txtSuaDapAnTracNghiem;
    // End of variables declaration//GEN-END:variables
}
