/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soandethi;

import docghidulieu.DocGhiDeThi;
import docghidulieu.DocGhiDuLieu;
import docghidulieu.PhuongThucChung;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.DeThi;
import model.MonHoc;
import static soandethi.XayDungDeThi.PATH;

/**
 *
 * @author Jeremie
 */
public class XoaDeThi extends javax.swing.JFrame {

    static final String PATH = "src/data/dsmonhoc.txt";
    MonHoc monHoc;
    ArrayList<MonHoc> dsMonHoc;
    DocGhiDuLieu docGhiDuLieu;
    ArrayList<DeThi> dsDeThi;
    DefaultListModel<String> dlDeThi;
    String pathDeThi;

    public XoaDeThi() {
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setTitle("Xóa đề thi");
        monHoc = new MonHoc();
        dsMonHoc = new ArrayList<>();
        docGhiDuLieu = new DocGhiDuLieu();
        dsMonHoc = docGhiDuLieu.docFile(PATH);
        hienThiTenCuaMonHocDuocChon();
        dlDeThi = new DefaultListModel<>();
        pathDeThi = "src/data/" + monHoc.getTenMonHoc();
        layDanhSachDeThi();
        listDeThi.setModel(dlDeThi);
    }
    
    private void hienThiTenCuaMonHocDuocChon() {
        System.out.println("Vị trí được chọn " + ChonMonHoc.viTriMonHocDuocChon);
        monHoc = dsMonHoc.get(ChonMonHoc.viTriMonHocDuocChon);
        System.out.println("So chuong mon hoc:"+monHoc.getSoChuong());
        txtTenMonHocDuocChon.setText(monHoc.getTenMonHoc());
    }
    
    private void layDanhSachDeThi() {
        dsDeThi = new ArrayList<>();
        File file = new File(pathDeThi);
        String path1;
        DeThi deThi;
        DocGhiDeThi dgdt = new DocGhiDeThi();
        String[] listFile = file.list();
        for(int i =0; i<listFile.length; i++){
            if(listFile[i].indexOf("DeThi") != -1){
            path1 = pathDeThi+"/"+listFile[i];
            deThi = dgdt.docDeThi(path1);
            dsDeThi.add(deThi);
            dlDeThi.addElement(deThi.getTenDeThi()+"     Kỳ: "+deThi.getKy()+"   Năm học: "+deThi.getNamHoc());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listDeThi = new javax.swing.JList<>();
        txtTenMonHocDuocChon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listDeThi);

        txtTenMonHocDuocChon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTenMonHocDuocChon.setForeground(new java.awt.Color(204, 0, 0));
        txtTenMonHocDuocChon.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách đề thi của :");

        btnDel.setBackground(new java.awt.Color(255, 204, 255));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 255, 204));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtTenMonHocDuocChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDel, btnHuy});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMonHocDuocChon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int n = listDeThi.getSelectedIndex();
        String tenDeThi = listDeThi.getSelectedValue().substring(0, listDeThi.getSelectedValue().indexOf(" ")); 
        if(n!=-1){
            dlDeThi.remove(n);
            dsDeThi.remove(n);
            File file = new File ("src\\data\\" + monHoc.getTenMonHoc()+"\\"+tenDeThi);
            file.delete();
            PhuongThucChung.showMessages("Bạn vừa xóa: "+tenDeThi);            
        }else{
            PhuongThucChung.showMessages("Hãy chọn 1 đề thi");
        }
        dispose();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XoaDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XoaDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XoaDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XoaDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XoaDeThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listDeThi;
    private javax.swing.JLabel txtTenMonHocDuocChon;
    // End of variables declaration//GEN-END:variables
}
